[package]
name = "tabiew"
version = "0.2.1"
authors = ["Shayan Hashemi <shshemi@gmail.com>"]
license = "MIT"
edition = "2021"
description = "A simple demonstration crate"
repository = "https://github.com/shshemi/tabiew"
documentation = "https://docs.rs/tabiew"
homepage = "https://github.com/shshemi/tabiew"

[[bin]]
name="tw"
path="src/main.rs"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
crossterm = "0.27.0"
itertools = "0.12.1"
polars = { version = "0.39.2", features = ["dtype-decimal", "lazy", "polars-sql"] }
polars-sql = "0.39.2"
ratatui = "0.26.0"
tui-textarea = "0.4.0"

[package.metadata.deb]
license-file = [ "LICENSE", "4" ]
depends = "$auto"
extended-description = """
Tabiew is a lightweight, terminal-based application designed to help view and query CSV files directly in your terminal.
"""
section = "utils"
priority = "optional"
assets = [
    [ "target/release/tw", "/usr/local/bin/tw", "0755" ],
]

[profile.release]
lto = true
strip = true
opt-level = 3
codegen-units = 1
panic = 'abort'