[package]
name = "tabiew"
version = "0.1.0"
authors = ["Shayan Hashemi <shshemi@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
crossterm = "0.27.0"
polars = { version = "0.39.2", features = ["dtype-decimal", "lazy", "polars-sql"] }
polars-sql = "0.39.2"
# polars-sql = "0.39.2"
ratatui = "0.26.0"
tui-textarea = "0.4.0"
