name: Manual Release

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Version bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  build-and-run:
    name: Build & Run on ${{ matrix.os }} / ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
          # MacOS
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          # Windows
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-11-arm
            target: aarch64-pc-windows-msvc

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
          components: clippy

      # Cache dependencies to speed up builds
      - name: Cache Cargo Registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-cargo-

      # Linux build
      - name: Install Cross
        if: matrix.os == 'ubuntu-latest'
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build and Test (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cross build --release --verbose --target ${{ matrix.target }}
          cross test --release --verbose --target ${{ matrix.target }}

      - name: Install Cargo Deb and RPM
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo install cargo-deb --version 2.11.1 --force
          cargo install cargo-generate-rpm --version 0.16.0 --force

      - name: Generate Deb and RPM Packages
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo deb --no-build --output tabiew-${{ matrix.target }}.deb --target ${{ matrix.target }}
          cargo generate-rpm --no-build --output tabiew-${{ matrix.target }}.rpm --target ${{ matrix.target }}

      # MacOS and Windows build 
      - name: Build and Test (Windows & MacOS)
        if: matrix.os != 'ubuntu-latest'
        run: |
          rustup target add ${{ matrix.target }}
          cargo build --release --target ${{ matrix.target }}
          cargo test --release --target ${{ matrix.target }}

      # Upload compiled binary to GitHub artifact
      - name: Upload Binary to GitHub Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tw-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/tw

      # Upload Deb and RPM
      - name: Upload Deb package to GitHub Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: tabiew-${{ matrix.target }}.deb
          path: tabiew-${{ matrix.target }}.deb

      - name: Upload RPM package to GitHub Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: tabiew-${{ matrix.target }}.rpm
          path: tabiew-${{ matrix.target }}.rpm