name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-x86-64-dist:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout to the latest version
        uses: actions/checkout@v4

      - name: Build
        run: |
          cargo build --release --verbose

      - name: Packaging assets
        shell: bash
        run: |
          cd target/
          ls -la
          cd release
          ls -la
          tar czvf tw-${{ matrix.target }}.tar.gz tw ../manual/*
          shasum -a 256 tw-${{ matrix.target }}.tar.gz > tw-${{ matrix.target }}.sha256

      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/tw-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
